local s,id=GetID()
function s.initial_effect(c)
	Kirafan.DuelStartMainCharacter(c)
	Kirafan.NoSummonMainCharacter(c)
	Kirafan.ThreeDrawMainCharacter(c)
	Kirafan.CannotBattleDestroyMainCharacter(c)
	Kirafan.CannotTurnPositionMainCharacter(c)
	Kirafan.TurnPositionMainCharacter(c)
	Kirafan.PierceDamageMainCharacter(c)
	Kirafan.Main2SkipMainCharacter(c)
	Kirafan.FieldTheRockMainCharacter(c)
	Kirafan.AttackCreaMainCharacter(c)
	Kirafan.ZeroBattleDamageMainCharacter(c)
	Kirafan.NoBattleTargetMainCharacter(c)
end